name: 中青阅读4（无）
on:
  workflow_dispatch:
  watch:
    types: started
  schedule:
     - cron: '0 3-21/3 * * *'
jobs:
  build:
    runs-on: ubuntu-latest       
    steps:
      - name: Checkout
        run: |
          git clone https://github.com/FerPina/ZQ-Body.git ~/js
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: npm install
        run: |
          cd ~/js
          npm install
          npm install cron
          npm install request
      - name: '运行 【中青阅读4】'
        run: |
          cd ~/js   
          node Task/Youth_AutoRead4.js
